Drivin/Controllers/TestimonialController.cs
using AutoMapper;
using Drivin.BL.Interfaces;
using Drivin.BL.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Store.BL.Helper;
using System.Collections.Generic;
using System;
using Drivin.DAL.Entity;
using Microsoft.AspNetCore.Authorization;

namespace Drivin.Controllers
{

    public class TestimonialController : Controller
	{
        #region ctor

        private readonly ITestimonialRep testimonialRep;
        private readonly IMapper mapper;


        public IMapper Mapper { get; }

        public TestimonialController(ITestimonialRep testimonialRep, IMapper mapper)
        {
            this.testimonialRep = testimonialRep;
            this.mapper = mapper;
        }
        #endregion
        [Authorize]

        #region Get Dashboard
        public IActionResult Index()
        {

            var data = testimonialRep.Get();
            var model = mapper.Map<IEnumerable<TestimonialVM>>(data);
            return View(model);
        }
        #endregion
        [Authorize]

        #region Create 
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(TestimonialVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.PhotoName = FileUpload.UploadFile("/wwwroot/Imgs", model.Photo);


                    var data = mapper.Map<Testimonial>(model);
                    testimonialRep.Create(data);
                    return RedirectToAction("Index");
                }
                return View(model);

            }
            catch (Exception)
            {
                return RedirectToAction("Error404");

            }



        }
        #endregion
        [Authorize]

        #region Details
        public IActionResult Details(int id)
        {
            var data = testimonialRep.GetById(id);
            var model = mapper.Map<TestimonialVM>(data);

            return View(model);

        }
        #endregion
        [Authorize]

        #region Edit 
        public IActionResult Edit(int id)
        {
            var data = testimonialRep.GetById(id);
            var model = mapper.Map<TestimonialVM>(data);

            return View(model);

        }
        [HttpPost]
        public IActionResult Edit(TestimonialVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.PhotoName = FileUpload.UploadFile("/wwwroot/Imgs", model.Photo);

                    var data = mapper.Map<Testimonial>(model);
                    testimonialRep.Edit(data);
                    return RedirectToAction("Index");
                }
                return View(model);

            }
            catch (Exception)
            {
                return View(model);
            }

        }
        #endregion


        #region Get Website
        public IActionResult WebsiteIndex()
        {

            var data = testimonialRep.Get();
            var model = mapper.Map<IEnumerable<TestimonialVM>>(data);
            return View(model);
        }
        #endregion

        [Authorize]

        #region Delete
        public IActionResult Delete(int id)
        {
            var data = testimonialRep.GetById(id);
            var model = mapper.Map<TestimonialVM>(data);
            return View(model);

        }
        [HttpPost]
        public IActionResult Delete(TestimonialVM model)
        {
            try
            {
                var data = mapper.Map<Testimonial>(model);
                testimonialRep.Delete(data);
                return RedirectToAction("Index");


            }
            catch (Exception)
            {
                return View(model);
            }

        }
        #endregion
    }
}

Drivin/Views/Testimonial/Create.cshtml
@model Drivin.BL.ViewModels.TestimonialVM
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}


<center>
	<h1>Create</h1>
</center>

<form asp-controller="Testimonial" asp-action="Create" enctype="multipart/form-data">


	<div class="form-group ">
		<label for="Name" class="form-control-label">Name  </label>
		<input placeholder="Enter Your Name" type="text" class="form-control " asp-for="Name">
	</div>
	<div class="form-group ">
		<label for="Comment" class="form-control-label">Comment  </label>
		<input placeholder="Add Comment" type="text" class="form-control " asp-for="Comment">
	</div>
	<div class="form-group">
		<label for="Photo">Photo</label>
		<input type="file" class="form-control-file form-control height-auto" asp-for="Photo">
	</div>


	<br />
	<input type="submit" value="Save" class="btn btn-success" />


</form>

Drivin/Views/Testimonial/Delete.cshtml
@model Drivin.BL.ViewModels.TestimonialVM

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h1>Delete</h1>


<form asp-controller="Testimonial" asp-action="Delete" enctype="multipart/form-data">

	<img src="~/Files/Imgs/@Model.PhotoName" class="rounded mx-auto d-block shadow-lg " style="height:200px ; width:300px" alt="...">
	<br />
	<div class="form-group">
		<label for="Id">Id</label>
		<input class="form-control" type="number" placeholder="Enter Header" asp-for="Id" disabled>
	</div>
	<br />
	<div class="form-group">
		<label for="Name">Name</label>
		<input class="form-control" type="text" placeholder="Enter Header" asp-for="Name" disabled>
	</div>
	<div class="form-group">
		<label for="Comment">Comment</label>
		<input class="form-control" type="text" placeholder="Enter Header" asp-for="Comment" disabled>
	</div>
	


	<br />
	<div class="border-top">
		<div class="card-body">
			<a asp-controller="Testimonial" asp-action="Index" type="submit" class="btn btn-primary">Back To Data</a>
			<input type="submit" value="Delete" class="btn btn-danger" />
		</div>
	</div>About

</form>

Drivin/Views/Testimonial/Details.cshtml
@model Drivin.BL.ViewModels.TestimonialVM

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h1>Details</h1>

<form asp-controller="Testimonial" asp-action="Create" enctype="multipart/form-data">

	<img src="~/Imgs/@Model.PhotoName" class="rounded mx-auto d-block shadow-lg " style="height:200px ; width:300px" alt="...">
	<br />
	<div class="form-group">
		<label for="Name">Name</label>
		<input class="form-control" type="text"asp-for="Name" disabled>
	</div>
	<div class="form-group">
		<label for="Comment">Comment</label>
		<input class="form-control" type="text"  asp-for="Comment" disabled>
	</div>




	<br />
	<div class="border-top">
		<div class="card-body">
			<a asp-controller="Testimonial" asp-action="Index" type="submit" class="btn btn-primary">Back To Data</a>
			<a asp-controller="Testimonial" asp-action="Edit" asp-route-id="@Model.Id" type="submit" class="btn btn-info">Edit</a>
			<a asp-controller="Testimonial" asp-action="Delete" asp-route-id="@Model.Id" type="submit" class="btn btn-danger">Delete</a>
		</div>
	</div>About

</form>

Drivin/Views/Testimonial/Edit.cshtml
@model Drivin.BL.ViewModels.TestimonialVM

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h1>Edit</h1>


<form asp-controller="Testimonial" asp-action="Edit" enctype="multipart/form-data" method="post">

	<img src="~/Imgs/@Model.PhotoName" class="rounded mx-auto d-block shadow-lg " style="height:200px ; width:300px" alt="...">
	<br />
	<div class="form-group">
		<label for="Name">Name</label>
		<input class="form-control" type="text" placeholder="Enter Header" asp-for="Name">
	</div>
	<div class="form-group">
		<label for="Comment">Comment</label>
		<input class="form-control" type="text" placeholder="Enter Header" asp-for="Comment">
	</div>
	

	<div class="form-group">
		<label for="Photo"> Image</label>
		<input type="file" class="form-control-file form-control height-auto" asp-for="Photo">
	</div>


	<br />
	<input type="submit" value="Save" class="btn btn-success" />

	<br />

</form>

Drivin/Views/Testimonial/Index.cshtml
@model IEnumerable<Drivin.BL.ViewModels.TestimonialVM>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<center>
    <h1>Index</h1>

</center>

<div class="container-fluid">
    <!-- ============================================================== -->
    <!-- Start Page Content -->
    <!-- ============================================================== -->
    <div class="row clearfix">
        <div class="col-md-12">



            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Team  Datatable</h5>
                    <div class="table-responsive">
                        <table id="zero_config" class="table table-striped table-bordered font-weight-bold text-center">
                            <thead>
                                <tr>
                                    <th scope="col">Id</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Comment</th>
                                    <th scope="col">Photo</th>
                                    <
                                    <th scope="col">Details</th>
                                    <th scope="col">Update</th>
                                    <th scope="col">Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Name</td>
                                        <td>@item.Comment</td>
                                        <td><img style="border-radius:50%" width="100" height="100" src="~/Imgs/@item.PhotoName" /></td>
                                        <td><a asp-controller="Testimonial" asp-action="Details" class="btn btn-primary" asp-route-id="@item.Id">Details</a></td>
                                        <td><a asp-controller="Testimonial" asp-action="Edit" class="btn btn-secondary" asp-route-id="@item.Id">Update</a></td>
                                        <td><a asp-controller="Testimonial" asp-action="Delete" class="btn btn-danger" asp-route-id="@item.Id">Delete</a></td>

                                    </tr>
                                }
                            </tbody>

                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>

Drivin/Views/Testimonial/WebsiteIndex.cshtml
@model IEnumerable<Drivin.BL.ViewModels.TestimonialVM>
@{
    ViewData["Title"] = "WebsiteIndex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- Page Header Start -->
<div class="container-fluid page-header py-6 my-6 mt-0 wow fadeIn" data-wow-delay="0.1s">
    <div class="container text-center">
        <h1 class="display-4 text-white animated slideInDown mb-4">@SharedLocalizer["Testimonial"]</h1>
        <nav aria-label="breadcrumb animated slideInDown">
            <ol class="breadcrumb justify-content-center mb-0">
                <li class="breadcrumb-item"><a class="text-white" href="#">@SharedLocalizer["Home"]</a></li>
                <li class="breadcrumb-item"><a class="text-white" href="#">@SharedLocalizer["Pages"]</a></li>
                <li class="breadcrumb-item text-primary active" aria-current="page">@SharedLocalizer["Testimonial"]</li>
            </ol>
        </nav>
    </div>
</div>
<!-- Page Header End -->
<!-- Testimonial Start -->
<div class="container-xxl py-6">
    <div class="container">
        <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 500px;">
            <h6 class="text-primary text-uppercase mb-2">@SharedLocalizer["Testimonial"]</h6>
            <h1 class="display-6 mb-4">@SharedLocalizer["What Our Clients Say"]!</h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-8 wow fadeInUp" data-wow-delay="0.1s">
                <div class="owl-carousel testimonial-carousel">
                    @foreach (var item in Model)
                   {
                        <div class="testimonial-item text-center">
                            <div class="position-relative mb-5">
                                <img class="img-fluid rounded-circle mx-auto" src="~/Imgs/@item.PhotoName" alt="">
                                <div class="position-absolute top-100 start-50 translate-middle d-flex align-items-center justify-content-center bg-white rounded-circle" style="width: 60px; height: 60px;">
                                    <i class="fa fa-quote-left fa-2x text-primary"></i>
                                </div>
                            </div>
                            <p class="fs-4">@item.Comment</p>
                            <hr class="w-25 mx-auto">
                            <h5>@item.Name</h5>
                            <span>@SharedLocalizer["Profession"]</span>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
</div>
<!-- Testimonial End -->