Drivin/Controllers/AboutController.cs
using AutoMapper;
using Drivin.BL.Interfaces;
using Drivin.BL.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System;
using Drivin.DAL.Entity;
using Store.BL.Helper;
using Microsoft.AspNetCore.Authorization;

namespace Drivin.Controllers
{

    public class AboutController : Controller
    {
        #region ctor

        private readonly IAboutRep aboutRep;
        private readonly IMapper mapper;


        public IMapper Mapper { get; }

        public AboutController(IAboutRep aboutRep, IMapper mapper)
        {
            this.aboutRep = aboutRep;
            this.mapper = mapper;
        }
        #endregion
        [Authorize]

        #region Get Dashboard
        public IActionResult Index()
        {

            var data = aboutRep.Get();
            var model = mapper.Map<IEnumerable<AboutVM>>(data);
            return View(model);
        }
        #endregion
        [Authorize]

        #region Create 
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(AboutVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.PhotoName = FileUpload.UploadFile("/wwwroot/Imgs", model.Photo);


                    var data = mapper.Map<About>(model);
                    aboutRep.Create(data);
                    return RedirectToAction("Index");
                }
                return View(model);

            }
            catch (Exception)
            {
                return RedirectToAction("Error404");

            }



        }
        #endregion
        [Authorize]

        #region Details
        public IActionResult Details(int id)
        {
            var data = aboutRep.GetById(id);
            var model = mapper.Map<AboutVM>(data);

            return View(model);

        }
        #endregion
        [Authorize]

        #region Edit 
        public IActionResult Edit(int id)
        {
            var data = aboutRep.GetById(id);
            var model = mapper.Map<AboutVM>(data);

            return View(model);

        }
        [HttpPost]
        public IActionResult Edit(AboutVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.PhotoName = FileUpload.UploadFile("/wwwroot/Imgs", model.Photo);

                    var data = mapper.Map<About>(model);
                    aboutRep.Edit(data);
                    return RedirectToAction("Index");
                }
                return View(model);

            }
            catch (Exception)
            {
                return View(model);
            }

        }
        #endregion
        

        #region Get 
        public IActionResult WebsiteIndex()
        {

            var data = aboutRep.Get();
            var model = mapper.Map<IEnumerable<AboutVM>>(data);
            return View(model);
        }
        #endregion

        [Authorize]

        #region Delete
        public IActionResult Delete(int id)
        {
            var data = aboutRep.GetById(id);
            var model = mapper.Map<AboutVM>(data);
            return View(model);

        }
        [HttpPost]
        public IActionResult Delete(AboutVM model)
        {
            try
            {
                var data = mapper.Map<About>(model);
                aboutRep.Delete(data);
                return RedirectToAction("Index");


            }
            catch (Exception)
            {
                return View(model);
            }

        }
        #endregion
    }
}

Drivin/Controllers/ContactController.cs
using AutoMapper;
using Drivin.BL.Interfaces;
using Drivin.BL.ViewModels;
using Drivin.DAL.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace Drivin.Controllers
{

    public class ContactController : Controller
    {
        #region ctor

        private readonly IContactRep contactRep;
        private readonly IMapper mapper;


        public IMapper Mapper { get; }

        public ContactController(IContactRep contactRep, IMapper mapper)
        {
            this.contactRep = contactRep;
            this.mapper = mapper;
        }
        #endregion
        [Authorize]

        #region Get Dashboard
        public IActionResult DashboardIndex()
        {

            var data = contactRep.Get();
            var model = mapper.Map<IEnumerable<ContactVM>>(data);
            return View(model);
        }
        #endregion
        [Authorize]

        #region Create 
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ContactVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {


                    var data = mapper.Map<Contact>(model);
                    contactRep.Create(data);
                    return RedirectToAction("Index");
                }
                return View(model);

            }
            catch (Exception)
            {
                return RedirectToAction("Error404");

            }



        }
        #endregion
        [Authorize]

        #region Details
        public IActionResult Details(int id)
        {
            var data = contactRep.GetById(id);
            var model = mapper.Map<ContactVM>(data);

            return View(model);

        }
        #endregion
        [Authorize]

        #region Edit 
        public IActionResult Edit(int id)
        {
            var data = contactRep.GetById(id);
            var model = mapper.Map<ContactVM>(data);

            return View(model);

        }
        [HttpPost]
        public IActionResult Edit(ContactVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var data = mapper.Map<Contact>(model);
                    contactRep.Edit(data);
                    return RedirectToAction("Index");
                }
                return View(model);

            }
            catch (Exception)
            {
                return View(model);
            }

        }
        #endregion


        #region Get 
        public IActionResult Index()
        {

            var data = contactRep.Get();
            var model = mapper.Map<IEnumerable<ContactVM>>(data);
            return View(model);
        }
        #endregion

        [Authorize]

        #region Delete
        public IActionResult Delete(int id)
        {
            var data = contactRep.GetById(id);
            var model = mapper.Map<ContactVM>(data);
            return View(model);

        }
        [HttpPost]
        public IActionResult Delete(ContactVM model)
        {
            try
            {
                var data = mapper.Map<Contact>(model);
                contactRep.Delete(data);
                return RedirectToAction("Index");


            }
            catch (Exception)
            {
                return View(model);
            }

        }
        #endregion

    }
}

Drivin/Controllers/CoursesController.cs
using AutoMapper;
using Drivin.BL.Interfaces;
using Drivin.BL.ViewModels;
using Drivin.DAL.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Store.BL.Helper;
using System;
using System.Collections.Generic;

namespace Drivin.Controllers
{

    public class CoursesController : Controller
    {
        #region ctor

        private readonly ICoursesRep coursesRep;
        private readonly IMapper mapper;



        public CoursesController(ICoursesRep coursesRep, IMapper mapper)
        {
            this.coursesRep = coursesRep;
            this.mapper = mapper;
        }
        #endregion
        [Authorize]

        #region Get Dashboard
        public IActionResult Index()
        {

            var data = coursesRep.Get();
            var model = mapper.Map<IEnumerable<CoursesVM>>(data);
            return View(model);
        }
        #endregion
        [Authorize]

        #region Create 
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CoursesVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.PhotoName = FileUpload.UploadFile("/wwwroot/Imgs", model.Photo);
                   


                    var data = mapper.Map<Courses>(model);
                    coursesRep.Create(data);
                    return RedirectToAction("Index");
                }
                return View(model);

            }
            catch (Exception)
            {
                return RedirectToAction("Error404");

            }



        }
        #endregion
        [Authorize]

        #region Details
        public IActionResult Details(int id)
        {
            var data = coursesRep.GetById(id);
            var model = mapper.Map<CoursesVM>(data);

            return View(model);

        }
        #endregion
        [Authorize]

        #region Edit 
        public IActionResult Edit(int id)
        {
            var data = coursesRep.GetById(id);
            var model = mapper.Map<CoursesVM>(data);

            return View(model);

        }
        [HttpPost]
        public IActionResult Edit(CoursesVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.PhotoName = FileUpload.UploadFile("/wwwroot/Imgs", model.Photo);
                
                    var data = mapper.Map<Courses>(model);
                    coursesRep.Edit(data);
                    return RedirectToAction("Index");
                }
                return View(model);

            }
            catch (Exception)
            {
                return View(model);
            }

        }
        #endregion


        #region Get 
        public IActionResult WebsiteIndex()
        {

            var data = coursesRep.Get();
            var model = mapper.Map<IEnumerable<CoursesVM>>(data);
            return View(model);
        }
        #endregion

        [Authorize]

        #region Delete
        public IActionResult Delete(int id)
        {
            var data = coursesRep.GetById(id);
            var model = mapper.Map<CoursesVM>(data);
            return View(model);

        }
        [HttpPost]
        public IActionResult Delete(CoursesVM model)
        {
            try
            {
                var data = mapper.Map<Courses>(model);
                coursesRep.Delete(data);
                return RedirectToAction("Index");


            }
            catch (Exception)
            {
                return View(model);
            }

        }
        #endregion
    }
}

Drivin/Controllers/OurTeamController.cs
using AutoMapper;
using Drivin.BL.Interfaces;
using Drivin.BL.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Store.BL.Helper;
using System.Collections.Generic;
using System;
using Drivin.DAL.Entity;
using Microsoft.AspNetCore.Authorization;

namespace Drivin.Controllers
{

    public class OurTeamController : Controller
	{
        #region ctor

        private readonly IOurTeamRep ourTeamRep;
        private readonly IMapper mapper;


        public IMapper Mapper { get; }

        public OurTeamController(IOurTeamRep ourTeamRep, IMapper mapper)
        {
            this.ourTeamRep = ourTeamRep;
            this.mapper = mapper;
        }
        #endregion
        [Authorize]

        #region Get Dashboard
        public IActionResult Index()
        {

            var data = ourTeamRep.Get();
            var model = mapper.Map<IEnumerable<OurTeamVM>>(data);
            return View(model);
        }
        #endregion
        [Authorize]

        #region Create 
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(OurTeamVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.PhotoName = FileUpload.UploadFile("/wwwroot/Imgs", model.Photo);



                    var data = mapper.Map<OurTeam>(model);
                    ourTeamRep.Create(data);
                    return RedirectToAction("Index");
                }
                return View(model);

            }
            catch (Exception)
            {
                return RedirectToAction("Error404");

            }



        }
        #endregion
        [Authorize]

        #region Details
        public IActionResult Details(int id)
        {
            var data = ourTeamRep.GetById(id);
            var model = mapper.Map<OurTeamVM>(data);

            return View(model);

        }
        #endregion
        [Authorize]

        #region Edit 
        public IActionResult Edit(int id)
        {
            var data = ourTeamRep.GetById(id);
            var model = mapper.Map<OurTeamVM>(data);

            return View(model);

        }
        [HttpPost]
        public IActionResult Edit(OurTeamVM model)
        {
            try
            {
                if (ModelState.IsValid)
                {
 
                    model.PhotoName = FileUpload.UploadFile("/wwwroot/Imgs", model.Photo);
                    var data = mapper.Map<OurTeam>(model);
                    ourTeamRep.Edit(data);
                    return RedirectToAction("Index");
                }
                return View(model);

            }
            catch (Exception)
            {
                return View(model);
            }

        }
        #endregion


        #region Get 
        public IActionResult WebsiteIndex()
        {

            var data = ourTeamRep.Get();
            var model = mapper.Map<IEnumerable<OurTeamVM>>(data);
            return View(model);
        }
        #endregion

        [Authorize]

        #region Delete
        public IActionResult Delete(int id)
        {
            var data = ourTeamRep.GetById(id);
            var model = mapper.Map<OurTeamVM>(data);
            return View(model);

        }
        [HttpPost]
        public IActionResult Delete(OurTeamVM model)
        {
            try
            {
                var data = mapper.Map<OurTeam>(model);
                ourTeamRep.Delete(data);
                return RedirectToAction("Index");


            }
            catch (Exception)
            {
                return View(model);
            }

        }
        #endregion

    }
}

Drivin/Views/Shared/LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

Drivin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<style>
    svg{
        height:30px; 
        width:30px;
    }
</style>
<head>
    <meta charset="utf-8">
    <title>@SharedLocalizer["Driving School Website Template"]</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="~/Website/img/carlogo.png" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/Website/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/Website/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/Website/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/Website/css/style.css" rel="stylesheet">
</head>

<body>
    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-grow text-primary" role="status"></div>
    </div>
    <!-- Spinner End -->
    <!-- Topbar Start -->
    <div class="container-fluid bg-dark text-light p-0">
        <div class="row gx-0 d-none d-lg-flex">
            <div class="col-lg-7 px-5 text-start">
                <div class="h-100 d-inline-flex align-items-center me-4">
                    <small class="fa fa-map-marker-alt text-primary me-2"></small>
                    <small>@SharedLocalizer["123 Cairo , Cairo-Egypt"]123 Cairo , Cairo-Egypt</small>
                </div>
                <div class="h-100 d-inline-flex align-items-center">
                    <small class="far fa-clock text-primary me-2"></small>
                    <small>Date : @DateTime.Now.Date </small>
                </div>
            </div>
            <div class="col-lg-5 px-5 text-end">
                <div class="h-100 d-inline-flex align-items-center me-4">
                    <small class="fa fa-phone-alt text-primary me-2"></small>
                    <small>+01065424443</small>
                </div>
                <div class="h-100 d-inline-flex align-items-center mx-n2">
                    <a class="btn btn-square btn-link rounded-0 border-0 border-end border-secondary" href="https://www.facebook.com/shehab.hassan.161"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-square btn-link rounded-0 border-0 border-end border-secondary" href="https://twitter.com/ShehabH14728073"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-square btn-link rounded-0 border-0 border-end border-secondary" href="https://www.linkedin.com/in/shehab-hassan-5a426b211/"><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-square btn-link rounded-0"asp-controller = "" asp-action="" a><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top p-0">
        <a asp-controller="Home" asp-action="Index" class="navbar-brand d-flex align-items-center border-end px-4 px-lg-5">
            <h2 class="m-0"><i class="fa fa-car text-primary me-2"></i>@SharedLocalizer["Drivin"]</h2>
        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a asp-controller="Home" asp-action="Index" class="nav-item nav-link">@SharedLocalizer["Home"]</a>
                <a asp-controller="About" asp-action="WebsiteIndex" class="nav-item nav-link">@SharedLocalizer["About"]</a>
                <a asp-controller="Courses" asp-action="WebsiteIndex" class="nav-item nav-link">@SharedLocalizer["Courses"]</a>
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">@SharedLocalizer["Pages"]</a>
                    <div class="dropdown-menu bg-light m-0">
                        <a asp-controller="Appointment" asp-action="WebsiteIndex" class="dropdown-item">@SharedLocalizer["Appointment"]</a>
                        <a asp-controller="OurTeam" asp-action="WebsiteIndex" class="dropdown-item">@SharedLocalizer["Our Team"]</a>
                        <a asp-controller="Testimonial" asp-action="WebsiteIndex" class="dropdown-item">@SharedLocalizer["Testimonial"]</a>
                    </div>
                </div>


                <a asp-controller="Contact" asp-action="Index" class="nav-item nav-link active">@SharedLocalizer["Contact"]</a>

                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><img src="~/Website/img/languages.png"  style="height:30px; width:30px;"/></a>
                    <div class="dropdown-menu bg-light m-0">
                        <a class="dropdown-item d-flex justify-content-between"
                           href="@Url.Action("SetLanguage", "Language", new {
                                                  culture = "en-US",
                                                  returnUrl = Context.Request.Path + Context.Request.QueryString
                                              })">
                            <img src="~/Website/img/usa.jpg" width="25" height="15" class="mt-1" />
                            <span>English</span>
                        </a>
                        <a class="dropdown-item d-flex justify-content-between"
                           href="@Url.Action("SetLanguage", "Language", new {
                                                  culture = "ar-EG",
                                                  returnUrl = Context.Request.Path + Context.Request.QueryString
                                              })">
                            <img src="~/Website/img/Egypt.jpg" width="25" height="15" class="mt-1" />
                            <span>Arabic</span>
                        </a>
                    </div>
                </div>
                    
                   
                </a>
                
            </div>
            <a asp-controller="Contact" asp-action="Index" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">@SharedLocalizer["Get Started"]<i class="fa fa-arrow-right ms-3"></i></a>
        </div>
    </nav>
    <!-- Navbar End -->
   
    <!-- Contact Start -->

    @RenderBody()


    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer my-6 mb-0 py-6 wow fadeIn" data-wow-delay="0.1s">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-white mb-4">@SharedLocalizer["Get In Touch"]</h4>
                    <h2 class="text-primary mb-4"><i class="fa fa-car text-white me-2"></i>@SharedLocalizer["Drivin"]</h2>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>@SharedLocalizer["Cairo , Cairo - Egypt"]</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+01065424443</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>shehabhassan.dev@gmail.com</p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-light mb-4">@SharedLocalizer["Quick Links"]</h4>
                    <a class="btn btn-link" asp-controller="About" asp-action="WebsiteIndex">@SharedLocalizer["About Us"]</a>
                    <a class="btn btn-link" asp-controller="Contact" asp-action="Index">@SharedLocalizer["Contact Us"]</a>
                    <a class="btn btn-link" asp-controller="Courses" asp-action="WebsiteIndex">@SharedLocalizer["Our Services"]</a>
                    <a class="btn btn-link" asp-controller="OurTeam" asp-action="WebsiteIndex">@SharedLocalizer["Terms"] & @SharedLocalizer["Condition"]</a>
                    <a class="btn btn-link" asp-controller="Contact" asp-action="Index">@SharedLocalizer["Support"]</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-light mb-4">@SharedLocalizer["Popular Links"]</h4>
                    <a class="btn btn-link" asp-controller="About" asp-action="WebsiteIndex">@SharedLocalizer["About Us"]</a>
                    <a class="btn btn-link" asp-controller="Contact" asp-action="Index">@SharedLocalizer["Contact Us"]</a>
                    <a class="btn btn-link" asp-controller="Courses" asp-action="WebsiteIndex">@SharedLocalizer["Our Services"]</a>
                    <a class="btn btn-link" asp-controller="OurTeam" asp-action="WebsiteIndex">@SharedLocalizer["Terms"] & @SharedLocalizer["Condition"]</a>
                    <a class="btn btn-link" asp-controller="Contact" asp-action="Index">@SharedLocalizer["Support"]</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-light mb-4">@SharedLocalizer["Newsletter"]</h4>
                    <form action="">
                        <div class="input-group">
                            <input type="text" class="form-control p-3 border-0" placeholder="Your Email Address">
                            <button class="btn btn-primary">@SharedLocalizer["Sign Up"]</button>
                        </div>
                    </form>
                    <h6 class="text-white mt-4 mb-3">@SharedLocalizer["Follow Us"]</h6>
                    <div class="d-flex pt-2">
                        <a class="btn btn-square btn-outline-light me-1" href="https://twitter.com/ShehabH14728073"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-square btn-outline-light me-1" href="https://www.facebook.com/shehab.hassan.161"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-square btn-outline-light me-1"asp-controller = "" asp-action="" a><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-square btn-outline-light me-0" href="https://www.linkedin.com/in/shehab-hassan-5a426b211/"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Copyright Start -->
    <div class="container-fluid copyright text-light py-4 wow fadeIn" data-wow-delay="0.1s">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; @DateTime.Now.Year <a href="#">Drivin </a>,@SharedLocalizer["All Right Reserved"] .
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                    @SharedLocalizer["Designed By"]  <a href="https://htmlcodex.com">HTML Codex</a>
                    <br>@SharedLocalizer["Coding By"]: <a href="https://www.linkedin.com/in/shehab-hassan-5a426b211/" target="_blank">@SharedLocalizer["Shehab"] @SharedLocalizer["Hassan"]</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Copyright End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Website/lib/wow/wow.min.js"></script>
    <script src="~/Website/lib/easing/easing.min.js"></script>
    <script src="~/Website/lib/waypoints/waypoints.min.js"></script>
    <script src="~/Website/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/Website/js/main.js"></script>
</body>

</html>